local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, {desc = "Find file"})
vim.keymap.set('n', '<leader>p<C-p>', builtin.git_files, {desc = "Find git files"})
vim.keymap.set('n', '<leader>ps', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
    end, {desc = "Grep project"})
vim.keymap.set('n', '<leader>pg', builtin.live_grep, {desc = "Live grep"})
vim.keymap.set('n', '<leader>pb', builtin.buffers, {desc = "Find buffers"})
-- vim.keymap.set('n', '<leader>fh', builtin.help_tags, {})
